// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMiYQCrMCh1uEqsW4Jsp55CTiWf9TC38',
    appId: '1:133090326250:web:903864b629033920b2c993',
    messagingSenderId: '133090326250',
    projectId: 'flower-shop-f1e83',
    authDomain: 'flower-shop-f1e83.firebaseapp.com',
    storageBucket: 'flower-shop-f1e83.appspot.com',
    measurementId: 'G-PLDCQTJX1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5XLnzp5irytKU45ReUAmv_0eATKwK6iE',
    appId: '1:133090326250:android:e030710b6fb28a05b2c993',
    messagingSenderId: '133090326250',
    projectId: 'flower-shop-f1e83',
    storageBucket: 'flower-shop-f1e83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN87ahsogWp8udblTSNYa75kH0OtQm6Qc',
    appId: '1:133090326250:ios:bfd828ee75ea9d0cb2c993',
    messagingSenderId: '133090326250',
    projectId: 'flower-shop-f1e83',
    storageBucket: 'flower-shop-f1e83.appspot.com',
    iosBundleId: 'com.example.flowerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN87ahsogWp8udblTSNYa75kH0OtQm6Qc',
    appId: '1:133090326250:ios:bfd828ee75ea9d0cb2c993',
    messagingSenderId: '133090326250',
    projectId: 'flower-shop-f1e83',
    storageBucket: 'flower-shop-f1e83.appspot.com',
    iosBundleId: 'com.example.flowerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNMiYQCrMCh1uEqsW4Jsp55CTiWf9TC38',
    appId: '1:133090326250:web:ad0ed7534fa32038b2c993',
    messagingSenderId: '133090326250',
    projectId: 'flower-shop-f1e83',
    authDomain: 'flower-shop-f1e83.firebaseapp.com',
    storageBucket: 'flower-shop-f1e83.appspot.com',
    measurementId: 'G-NBRL8CKKXV',
  );
}
